server {
    listen 80;
    absolute_redirect off;

    location = / {
        return 301 /admin/;
    }

    location = /admin {
        return 301 /admin/;
    }

    location /admin/ {
        root /usr/share/nginx/html;
        index index.html;

        try_files $uri $uri/ /admin/index.html;
    }
}