import { useEffect, useState } from 'react';
import type { AppProps } from 'next/app'
import Head from 'next/head';

import { ToastContainer, toast } from "react-toastify";
import { initializeAPI } from "../api/base-api";
import baseURL from "../constants/api-url";
import { AppContext } from "../libs/contextLib";

import 'react-toastify/dist/ReactToastify.css';
import '../styles/globals.css'

function MyApp({ Component, pageProps }: AppProps) {
  const [user, setUser] = useState(null);
  const [token, setToken] = useState(null);

  initializeAPI({
    baseURL,
    onError: toast.error,
    token,
    setToken,
    onBadToken: () => {
      setToken(null);
      setUser(null);
    },
  });

  useEffect(() => {
    const user = JSON.parse(localStorage.getItem("user"));
    const token = localStorage.getItem("token");
    if (user && token) {
      setUser(user);
      setToken(token);
    }
  }, []);

  return (
    <AppContext.Provider value={{
      user,
      setUser,
      token,
      setToken
    }}>
      <Head>
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap"
          rel="stylesheet"
        />
        <title>Semcomp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ToastContainer hideProgressBar />
      <Component {...pageProps} />
    </AppContext.Provider>
  );
}

export default MyApp
