version: "2"
services:
  server:
    restart: always
    build: .
    ports:
      - "8090:8090"
    container_name: server
    depends_on:
      - redis
    links:
      - redis
  redis:
    restart: always
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
  mongodb:
    image: mongo:5.0.8
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./mongo-volume:/data/db
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=semcomp
