services:
  front-site:
    build: ./front-site
    container_name: front-site
    restart: always
    ports:
      - "127.0.0.1:5173:80"

  backoffice:
    build: ./front-backoffice
    container_name: backoffice
    restart: always
    ports:
      - "127.0.0.1:5174:80"

  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - "127.0.0.1:4000:4000"
    env_file:
      - ./backend/.env