
# services:
#   nginx:
#     image: nginx:alpine
#     container_name: semcomp-nginx
#     ports:
#       - "80:80"
#       - "443:443"
#     volumes:
#       # - ./nginx.conf:/etc/nginx/conf.d/default.conf
#       #
#       # - ./certs:/etc/letsencrypt
#     depends_on:
#       - front-site
#       - front-backoffice
#       - front-test
#       - backend

#   front-site:
#     build: ./packages/front-site
#     container_name: front-site
#     restart: always

#   # front-backoffice:
#   #   build: ./packages/front-backoffice
#   #   container_name: front-backoffice
#   #   restart: always

#   # front-test:
#   #   build: ./packages/front-test
#   #   container_name: front-test
#   #   restart: always

#   # backend:
#   #   build: ./packages/backend
#   #   container_name: backend
#   #   restart: always
#   #   expose:
#   #     - "4000"  
#   #   environment:
#   #     - NODE_ENV=production


services:
  front-site:
    build: ./front-site
    container_name: front-site
    ports:
      - "5173:5173"
    command: npm run dev -- --host
    restart: unless-stopped

  backoffice:
    build: ./front-backoffice
    container_name: backoffice
    ports:
      - "5174:5174"
    command: npm run dev -- --host
    restart: unless-stopped


  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: UsersDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: