services:
  front-site:
    build: ./front-site
    container_name: front-site
    restart: always
    ports:
      - "127.0.0.1:5173:80"

  backoffice:
    build: ./front-backoffice
    container_name: backoffice
    restart: always
    ports:
      - "127.0.0.1:5174:80"

  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - uploads_data:/app/uploads

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - ./backend/.env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  uploads_data:
