export type SponsorLogo = { src: string; alt: string; title: string };

const p = (company: string, file: string): SponsorLogo => ({
  src: `/img/previous_sponsors/${encodeURIComponent(company)}/${encodeURIComponent(file)}`,
  alt: company,
  title: company,
});

export const PREVIOUS_SPONSORS: SponsorLogo[] = [
  p("Acad Arena",        "LogoGradient@4x.png"),
  p("Accenture",         "icon-light.svg"),
  p("Alliage",           "path194.svg"),
  p("Alura",             "alura-light.svg"),
  p("AMD",               "full-dark.svg"),
  p("BemAgro",           "icone colorido para fundos escuros-web.svg"),
  p("BTG Pactual",       "BTGT.0002.DE.191118.OriginaisEletronicos_POS_CMYK_BTGPACTUAL_semrespiro.png"),
  p("CI&T",              "full-light.svg"),
  p("Cohere",            "full-light.svg"),
  p("CPqD",              "full-light.svg"),
  p("CSD",               "CSD branco.svg"),
  p("Desktop",           "LOGO 1.png"),
  p("EloGroup",          "logo.svg"),
  p("Ernst & Young",     "wikimedia-ey-logo-2019.svg"),
  p("Fundação Estudar",  "FE_aplicação.png"),
  p("Goldman Sachs",     "goldman-sachs-1.svg"),
  p("Google",            "full-light.svg"),
  p("Griaule",           "logo-griaule-cmyk-blue - notext.svg"),
  p("idwall",            "full-light.svg"),
  p("Inoa",              "Logo Horizontal Cores clean 300dpi - com margem.png"),
  p("Intel Software",    "icon-light.svg"),
  p("Loggi",             "logodownload-1.png"),
  p("LuizaLabs",         "iconape-1.png"),
  p("Neon",              "neon.logo (2).png"),
  p("Pagar.me",          "full-light.svg"),
  p("Porto Seguro",      "Porto Seguros_RGB_Horizontal-01.svg"),
  p("ProFUSION",         "Asset 52.svg"),
  p("Qive",              "Qive_originais de marca-03.png"),
  p("Raizen",            "wikimedia-original.svg"),
  p("Serasa",            "wikimedia-original.svg"),
  p("Tractian",          "seeklogo-preview.png"),
  p("Venturus",          "venturus.png"),
  p("Visagio",           "Logo-Grupo-Off.png"),
  p("Yara International","full-light.svg"),
];
