name: deploy-frontend
on:
  push:
    branches:
      - main 
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Build frontend
        run: cd /var/www/html/semcomp/packages/app && git pull && docker-compose up --build && rm -rf /var/www/html/build && cp /var/www/html/semcomp/packages/app/out /var/www/html/build -r
