name: sync-vm

on:
  push:
    branches:
      - new-site

jobs:
  sync:
    runs-on: self-hosted

    steps:
      - name: Sync repo
        run: |
          cd /var/www/html/site-semcomp/semcomp
          git fetch origin
          git checkout new-site
          git reset --hard origin/new-site
      - name: Restart Docker containers
        run: |
          whoami
          cd /var/www/html/site-semcomp/semcomp/new-site/packages/
          make restart
          